### PR TITLE
Fix changelog generation on windows

### LINKED ISSUE #130: Broken changelog for windows
In windows environment i try use `release-it-lerna-changelog` and my changelogs in release looks something like [this](https://github.com/Kolobok12309/release-it-test/releases/tag/0.0.2) and in console this (It's different releases)
```
�🚀 Let's release release-it-test (currently at 0.0.2)


Changelog:
* Add lerna (bd2d34c)
* Remove lerna (69ad898)
* Update release script (e7bea72)
* Merge pull request #3 from Kolobok12309/feature/second-feature (0adb363)
* Add second console.log (0e182df)
```
---
Trouble in shell exec for windows, you try exec command `D:\projects\release-it-test\node_modules\lerna-changelog\bin\cli.js --next-version=Unreleased --from=0.0.2`, but windows try open `*.js` file by default viewer, for me it VSCode.
If call `node ...`, or `lerna-changelog --next-version=Unreleased --from=0.0.2` all fine.

### PR DESCRIPTION
**Pull request by patricklx**
fixes #130 

same is also done for git, so why not?

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ export default class LernaChangelogGeneratorPlugin extends Plugin {
   }
 
   async _execLernaChangelog(from) {
-    let changelog = await this.exec(`${LERNA_PATH} --next-version=${UNRELEASED} --from=${from}`, {
+    let changelog = await this.exec(`node ${LERNA_PATH} --next-version=${UNRELEASED} --from=${from}`, {
```
Comment (rwjblue) [inline index.js:76]: This change seems like a great way to avoid the issue reported! Let's use `process.execPath` though to make sure we use the exact `node` that is being used (this is helpful in certain environments that dynamically determine `node` versions).

```suggestion
    let changelog = await this.exec(`${process.execPath} ${LERNA_PATH} --next-version=${UNRELEASED} --from=${from}`, {
```
